### ISSUE TITLE
Detector outline disappears after transform applied

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1380] opened 2023-03-29 22:18 UTC
when I add the detector outline, then apply a transform (eg reflect about horizontal), the detector outline disappears and never comes back. 
(maybe this will be fixed by automatically drawing the boxes in the other issue)

there is an error:

> Traceback (most recent call last):
  File "/Users/krygier1/miniconda3/envs/cHEX/lib/python3.10/site-packages/hexrd/ui/llnl_import_tool_dialog.py", line 289, in add_transform
    self.it.toggle_boundaries(show=True)
  File "/Users/krygier1/miniconda3/envs/cHEX/lib/python3.10/site-packages/hexrd/ui/interactive_template.py", line 133, in toggle_boundaries
    self.shape = self.raw_axes.patches.pop()
AttributeError: 'ArtistList' object has no attribute 'pop'

**Comment by bnmajor** [comment] 2023-04-18 20:36
@akrygier Were you seeing this behavior on master? Or was this on a specific release?

**Comment by akrygier** [comment] 2023-04-22 17:10
Sorry i missed this. I think it was resolved once I updated but I'll check
again next week.
- Andy

**Comment by psavery** [comment] 2023-04-27 16:23
This was fixed in #1413 just yesterday. It was caused by a recent change to that matplotlib API.

**Closed by psavery** 2023-04-27 16:23 UTC
