### ISSUE TITLE
Min/max colormap boxes don't update after "reset range" button

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#160] opened 2019-08-27 21:10 UTC
...until you refocus

**Comment by cryos** [comment] 2020-05-12 17:46
Can this be closed, or can we zero in on the remaining issue?

**Comment by joelvbernier** [comment] 2020-06-18 06:28
reset updates the boxes, but doesn't affect a change in the plot.

**Comment by psavery** [comment] 2020-06-18 12:41
It seems to be working for me on Linux. I'll give it a try on Mac too.

![Peek 2020-06-17 14-03](https://user-images.githubusercontent.com/9558430/85021164-727be680-b13f-11ea-990c-6d639dffa73a.gif)

**Comment by psavery** [comment] 2020-06-18 13:41
I just confirmed on Mac that something sketchy is going on!

It's true, the `Reset Range` button doesn't update the values in the boxes until you re-focus.

Then, the image doesn't update as well unless I change active windows and then come back.

**Comment by psavery** [comment] 2020-06-18 14:54
ContinuumIO/anaconda-issues#11297 might be similar.

**Comment by joelvbernier** [comment] 2020-06-19 00:53
Oh, Apple...

**Comment by psavery** [comment] 2020-06-19 16:01
Note that this also appears to happen for other buttons as well. For instance, if I try to click "Hide All" for the overlays, it doesn't update unless I make the main hexrd window lose focus and then re-gain focus.

**Comment by psavery** [comment] 2020-06-22 18:06
So yes, I think I have figured out the problem and have a solution as well.

This is the same issue as conda-forge/pyside2-feedstock#46

The problem is that PySide2 is not compatible with the python on anaconda (both in the `anaconda` and `conda-forge` channels). The reason is that the python on anaconda is being built using an older macOS SDK. [Qt requires newer versions of the SDK for building](https://doc.qt.io/qt-5/macos.html) (the latest requires 10.15), but you can still target older platforms for runtime (the latest supports 10.13). It looks like, in order for PySide2 to work properly, not only does Qt need to be built with a newer version of the SDK, but the python that is running it needs a newer version of the SDK as well.

This incompatibility problem results in some general bugginess in the UI. The most noticeable one is that, if a widget (such as a spinbox or a checkbox) gets set programmatically, it won't update in the UI until an update is caused another way (such as resizing the window or making the main window lose focus). The canvas also does not update if it is programmatically modified.

I was able to fix the issue locally by building a conda python package using macOS SDK 10.14, via the [python-feedstock](https://github.com/conda-forge/python-feedstock). This works with the latest PySide2 on conda-forge.

It looks like for now, we'll either need to find a conda package of python3.8 that is being built using a newer macOS SDK, or build it ourselves.

**Comment by psavery** [comment] 2020-06-22 19:01
This should be fixed for us, by the way, when conda-forge/conda-forge-ci-setup-feedstock#67 gets resolved.

**Comment by cjh1** [comment] 2020-07-27 14:12
@psavery I think its time to raise an issue against python-feedstock, now the  conda-forge/conda-forge-ci-setup-feedstock#67  is merged. Do you want to do it or shall I?

**Comment by cjh1** [comment] 2020-08-05 21:04
I raised a PR against [python-feedstock](https://github.com/conda-forge/python-feedstock/pull/371)

**Comment by psavery** [comment] 2020-09-08 16:09
This is now tracked in #505. Closing.

**Closed by psavery** 2020-09-08 16:09 UTC
Labels: bug, conda python mac issue
