### ISSUE TITLE
No conda packages for osx-arm64

### ISSUE THREAD

**Issue by rachelelim** [HEXRD/hexrdgui#1336] opened 2023-02-14 20:53 UTC
When trying to install the gui, it can't find pyside2 for some reason. I manually installed pyside2 (v5.15.8). Then when trying to launch the gui, it asks for h5py. When I try to install h5py there are a bunch of package dependency conflicts

**Comment by rachelelim** [comment] 2023-02-14 21:21
[hexrdgui_errors.pdf](https://github.com/HEXRD/hexrdgui/files/10736961/hexrdgui_errors.pdf)

**Comment by psavery** [comment] 2023-02-16 13:38
Hi @rachelelim. I see from the logs this is on an arm64 Mac. I have an arm64 Mac laptop I can also give this a try on. I'll get back with you soon.

**Comment by psavery** [comment] 2023-02-16 21:32
@rachelelim Can you try running the commands shown on the main README of this repository? So after this:

```bash
conda create -n hexrdgui_Feb23
conda activate hexrdgui_Feb23
```

Try this:
```bash
conda install -c hexrd -c conda-forge python=3.10 hexrdgui
```

You can run `hexrdgui` to see if it works.

And then, if you want to set up a development environment after that, proceed to this:
```bash
git clone https://github.com/HEXRD/hexrd.git
git clone https://github.com/HEXRD/hexrdgui.git
pip install -e hexrd
pip install -e hexrdgui
```

That seems to be working for me on my arm64 laptop.

**Comment by rachelelim** [comment] 2023-02-17 18:46
I tried that already and it wasn't working which is why I was doing it that convoluted way.
![Screen Shot 2023-02-17 at 10 45 55 AM](https://user-images.githubusercontent.com/21162319/219757981-28f946b4-b477-4d25-8ca0-00c3a0088f6c.png)

**Comment by psavery** [comment] 2023-02-18 20:38
My apologies @rachelelim. I missed that part, and when I tried it locally, I was apparently using the x86_64 version of conda.

The challenge is that the newer Apple computers with M1 chips have a different CPU architecture (arm64), which means all software must be recompiled to run on it. Fortunately, Apple did make it so that you can still run programs that use the older x86_64 architecture, but to do so with conda, you would need to download and use the x86_64 version of conda (not the arm64 version), which is what I was doing.

However, I did just build the arm64 conda packages for the latest versions of both hexrd and hexrdgui and uploaded them. So can you try [the above commands](https://github.com/HEXRD/hexrdgui/issues/1336#issuecomment-1433741390) again? It should work this time.

I did a quick test of the arm64 version and it seemed to work okay. However, you are going to be the first person to really use it, so let us know if you run into issues.

We need to set up some automation to generate the arm64 packages, but I don't know if that's possible right now. I'll post a separate issue for that.

**Comment by psavery** [comment] 2023-02-22 16:51
@rachelelim confirmed in #1338 that the package is now working for hexrdgui. We still need to automatically build and upload these packages for both quality and consistency, but that is being tracked in #1338 and hexrd/hexrd#499. Closing this issue.

**Closed by psavery** 2023-02-22 16:51 UTC

**Comment by psavery** [comment] 2023-10-19 19:40
@rachelelim We are now automatically building HEXRD arm64 packages (soon, we will have HEXRDGUI ones too). So if you `conda install -c hexrd/label/hexrd-prerelease -c conda-forge hexrd`, it will install the latest `hexrd` packages for `arm64`.

Even though GitHub actions added support for M1 runners, payment is required to use them. So cross-compiling ended up being easier instead, and cross-compiling appears to be working fine!
