### ISSUE TITLE
show SNIP button only works once

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#999] opened 2021-07-29 18:29 UTC
When I apply snip and then use the show SNIP button to display the snip, it works the first time. After closing that window, the show SNIP button does not do anything.

**Comment by psavery** [comment] 2021-07-29 21:51
This is actually a duplicate of #522, but that was closed without being fixed. I believe #1000 should fix this issue.

**Closed** 2021-07-29 21:56 UTC
