### ISSUE TITLE
Log scale not applied to polar view

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#184] opened 2019-10-10 23:59 UTC
has no effect on this polar image -- I removed the log scaling that was inside polarview; would be nice to toggle on/off in the GUI

**Comment by joelvbernier** [comment] 2020-02-21 20:05
Hmmm...  will poke around.  Also, did you removed the "fake" border application with the border overlay PR @psavery ?

**Comment by psavery** [comment] 2020-02-21 20:32
@joelvbernier Yep! Fake border is gone.

**Comment by joelvbernier** [comment] 2020-03-29 02:46
I am currently running the 0.7.1 package on a fresh Ubuntu install, and the log scale checkbox still appears to not be working properly.  First, there is no update to the canvas (exception is thrown), then if you click on the canvas to, e.g. zoom, it disappears entirely.  See traceback below -- looks like the log is getting invalid values.

```
Traceback (most recent call last):
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/hexrd/ui/color_map_editor.py", line 117, in update_norm
    self.image_tab_widget.set_norm(norm)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/hexrd/ui/image_tab_widget.py", line 215, in set_norm
    self.update_canvas_norms()
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/hexrd/ui/image_tab_widget.py", line 207, in update_canvas_norms
    canvas.set_norm(self.norm)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/hexrd/ui/image_canvas.py", line 454, in set_norm
    self.draw()
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 393, in draw
    self.figure.draw(self.renderer)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/figure.py", line 1736, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2630, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/image.py", line 626, in draw
    renderer, renderer.get_image_magnification())
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/image.py", line 917, in make_image
    magnification, unsampled=unsampled)
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/image.py", line 516, in _make_image
    output = self.norm(np.ma.masked_array(A_resampled, out_mask))
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/colors.py", line 1156, in __call__
    self._check_vmin_vmax()
  File "/home/joel/Applications/HEXRD-0.7.1/lib/python3.7/site-packages/matplotlib/colors.py", line 1145, in _check_vmin_vmax
    raise ValueError("minvalue must be positive")
ValueError: minvalue must be positive
```

**Comment by psavery** [comment] 2020-03-29 20:59
@joelvbernier I was able to reproduce this problem on the v0.7.1 package. 

It looks like the problem only occurs with specific datasets. It doesn't appear to occur with our simple "ge" test dataset (which is why I wasn't able to reproduce the problem earlier).

But I was able to cause this problem on the "mruby" example for the dexela config.

For a local build using the same dataset, there is also an exception, although the backtrace is slightly different. We can look into this.
```
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/color_map_editor.py", line 117, in update_norm
    self.image_tab_widget.set_norm(norm)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/image_tab_widget.py", line 215, in set_norm
    self.update_canvas_norms()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/image_tab_widget.py", line 207, in update_canvas_norms
    canvas.set_norm(self.norm)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/image_canvas.py", line 457, in set_norm
    self.draw()
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 619, in draw
    renderer, renderer.get_image_magnification())
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 881, in make_image
    unsampled=unsampled)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 482, in _make_image
    output = self.norm(np.ma.masked_array(A_resampled, out_mask))
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/colors.py", line 1096, in __call__
    raise ValueError("values must all be positive")
ValueError: values must all be positive
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 508, in _draw_idle
    self.draw()
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 619, in draw
    renderer, renderer.get_image_magnification())
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 881, in make_image
    unsampled=unsampled)
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/image.py", line 482, in _make_image
    output = self.norm(np.ma.masked_array(A_resampled, out_mask))
  File "/home/patrick/virtualenvs/hexrd/lib/python3.7/site-packages/matplotlib/colors.py", line 1096, in __call__
    raise ValueError("values must all be positive")
ValueError: values must all be positive
```

**Comment by psavery** [comment] 2020-03-30 11:04
An update here. It appears that the issue occurs if the `Minimum Value:` in the color map editor is 0. This causes the exception, since the matplotlib LogNorm must have positive `vmin` and `vmax` values.
![Screenshot from 2020-03-30 06-45-23](https://user-images.githubusercontent.com/9558430/77904771-16e24100-7253-11ea-8884-c293ae1abc3b.png)

Maybe one fix for this would be to make sure `min` is non-zero [here](https://github.com/HEXRD/hexrdgui/blob/042e19973ea713ea3cd0fad0eab673a3d0f6e5b9/hexrd/ui/color_map_editor.py#L113), by making it a small number like `1.e-8`, if it is zero? Some of the pixel values in the images are indeed zero, so I am assuming a minimum value of 0 in the color map is valid.

**Closed** 2020-04-29 17:57 UTC
Labels: bug, high priority
