### ISSUE TITLE
Strange behavior in Instrument Calibration widget

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#493] opened 2020-09-02 22:16 UTC
I've noticed some odd inconsistencies in the instrument calibration widget on the Mac -- haven't tested the same on linux yet but I'll try to and update this issue accordingly.

1. In the Slider View:
  - The labels for the tilt (X, Y ,Z) are misleading if you are using a tilt parameterization other than extrinsic XYZ; we should either update them to match the selected parameterization (if possible), or give them more generic names.
  - The spin controller widgets seem to be very restricted in terms of the precision of the number you can enter.  For example, I cannot enter '-90' in a tilt box.  I know we have hashed over this before, but ideally, we can decouple the displayed number of digits and what it can take as input (surely we must be able to do this, right?).  Either way, I need to be able to input more than one digit.  **_UPDATE_**: this seems to be a Mac thing as it is ok in Ubuntu -- oh boy...
2. In the Form View:
  - The field do not update with a change in the detector selector -- unless I toggle between one of the other tabs and back.
  - Regardless of the checkbox state in the tree view, any edits to the text input widgets affect no change in the underlying vaules; _i.e._, they disappear if I toggle to either of the other view tabs.
3. In the Tree View:
  - Not sure if we tried this before, but is it possible to change the units to degrees for the tilts if the chosen parameterization is not `None`?  The other two view modes are in degrees, but this is in radians for the tilts.

**Comment by psavery** [comment] 2020-09-08 17:53
For the X Y Z labels in the slider view, we can probably just add a function that sets them based on the current Euler angle convention. 

Indeed the spin controllers are restricted to two decimal places. Maybe the best option is to use the [ScientificSpinBox](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/scientificspinbox.py) instead?

The min and max of the spinboxes are dynamically set to match the min/max of the sliders. This min/max is determined via the range spin box in the tops of the groups. This is by design, and it restricts the range of values you can enter in the spinboxes so the slider can be moved to match it (which is probably why you couldn't enter "-90", if it was outside the slider range). We can re-design this, though, if that is desirable. Maybe if the user sets a value in the spinbox that is outside the slider range, we can reset the range so the new value is centered in the slider, for instance.

For the form view, the fields appear to update for me with the detector selector, and the edits to the text input widgets appear to affect the underlying values. I think these might be part of #505. The python binary we have uploaded should help.

For the tree view, we haven't tried that before. But we can do it I believe!

**Comment by cjh1** [comment] 2020-09-08 18:24
@joelvbernier Will try again with the new python package.

**Comment by bnmajor** [comment] 2020-09-08 21:25
#507 Updates the labels for tilt to match selected Euler angle convention and changes the units to degrees for tilts in tree view if convention is not `None`.

**Comment by cjh1** [comment] 2020-09-15 18:46
Closing reopen if necessary

**Closed by cjh1** 2020-09-15 18:46 UTC
Labels: bug, hedm, high priority, llnl
