### ISSUE TITLE
Add transform is greyed out after I add detector outline.

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#831] opened 2021-03-19 16:38 UTC
I don't know if this is by design, but I can only figure out where the holes are placed and what transforms to add once I load in the data and thean add the detector outline. I think other users might feel the same.
![output2](https://user-images.githubusercontent.com/15834451/111813359-55bf3b80-8896-11eb-8d20-5188ac864e57.gif)

**Comment by bnmajor** [comment] 2021-03-19 17:01
This is by design at the moment. An image must be loaded before the detector bounds can be drawn.

#793 was created to re-think the approach to the current LLNL workflow and would be a good place to include this feature change if it would be helpful. @saransh13 I am thinking it would maybe make sense to have the ability to apply transforms once the detector border is visible? Or do you have other behavior you would prefer to see?

**Comment by saransh13** [comment] 2021-03-19 20:43
Yeah, I think that feature will be very useful for figuring out the transform required in case the user doesn't already know.

**Comment by bnmajor** [comment] 2021-04-06 16:05
Fixed in #867

**Closed** 2021-04-06 19:40 UTC
Labels: enhancement
