### ISSUE TITLE
File>Open>Images loads up image but doesn't make the other options available for PXRDIP load

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#895] opened 2021-04-21 16:59 UTC
The select Image right below the instrument selection works but if the user opens image using the menu option, then the next steps are not initiated. 

https://user-images.githubusercontent.com/15834451/115592463-1b2b3300-a288-11eb-916a-b7bc61ed6a77.mov

**Comment by bnmajor** [comment] 2021-04-21 17:08
@saransh13 That is currently the expected behavior. The quick load option through the file menu is currently meant for processed imageseries and images need to be loaded through the import panel to access the import features. Do we want to change this so that images loaded through the quick-load menu option enable the import panel? Users would still be required to select the instrument on the panel first.

**Comment by saransh13** [comment] 2021-04-21 17:41
I just was confused since the image loads up fine and we have been using that option for all our tutorials. I think it'd be good for consistency. @joelvbernier thoughts?

**Comment by joelvbernier** [comment] 2021-04-21 19:15
The import tool and the load tool are inherently different @saransh13 -- the File --> Load path is for loading already cropped images, as it forces one image per detector.  The import tool is expecting you load a single image with all detector images in it for cropping.  There is no way to reconcile the behavior of the two functions.  

I do think that I will be getting rid of the "load data" tab and moving them to respective "File --> Import Image Data" items for HEDM, and pinhole camera analysis.  That way it is less likely someone will try to load already processed images using the (raw) import dialog.

Unless I am misunderstanding your gist...?

**Comment by bnmajor** [comment] 2021-04-27 15:29
@saransh13 @joelvbernier Will we be keeping the current behavior as-is for now? Or should we be re-thinking the expected behavior?

**Comment by joelvbernier** [comment] 2021-04-27 17:06
@saransh13 -- closing this, as that is not the intended use case for the import tool.  The File --> Open --> images is intended for images that _do not_ need the cropping tool

**Closed by joelvbernier** 2021-04-27 17:06 UTC
