### ISSUE TITLE
New errors in LLNL I/O

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#492] opened 2020-09-02 21:30 UTC
I am getting some new errors when I try to execute the LLNL I/O.  This is on the Mac (I'll try to reporduce on Ubuntu).

For TARDIS selected:

1. with overlays selected (_e.g._, from a saved state) I get the following exception
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 775, in update_all
    self.ui.image_tab_widget.load_images()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 119, in load_images
    self.load_images_untabbed()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 99, in load_images_untabbed
    self.image_canvases[0].load_images(
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 123, in load_images
    self.update_overlays()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 282, in update_overlays
    self.iviewer.update_overlay_data()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/raw_iviewer.py", line 17, in update_overlay_data
    update_overlay_data(self.instr, self.type)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/__init__.py", line 90, in update_overlay_data
    overlay['data'] = generator.overlay(display_mode)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/powder_diffraction.py", line 46, in overlay
    indices, ranges = self.plane_data.getMergedRanges()
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/crystallography.py", line 957, in getMergedRanges
    (tThRanges[:-1, 1] < tThRanges[1:, 0], True)
IndexError: too many indices for array
```
and the image doesn't load.  Note that we **do not** want to do overlays in the I/O graphics canvas, rather only after the images are loaded and processed.

2. when trying to use the rotate/translate tools, I am getting:
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/import_data_panel.py", line 139, in setup_translate
    self.it.disconnect_rotate()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/interactive_template.py", line 209, in disconnect_rotate
    self.parent.mpl_disconnect(self.button_drag_cid)
AttributeError: 'InteractiveTemplate' object has no attribute 'button_drag_cid'
```
But if I switch focus and re-focus the app, then it works (?).  Also, I can only get the rotate to start working I use right-click.  Lastly, the detector outline will only draw if I change focus and re-focus as well.  I suspect that these are Mac-specific problems, but many of the users are on Macs :-/
3. when adding a transform using the interactor I get:
```Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/import_data_panel.py", line 124, in add_transform
    self.it.update_image(HexrdConfig().image('default', 0))
AttributeError: 'NoneType' object has no attribute 'update_image'
```
although it seems to be applied.
4. after cropping, the axes limits don't seem to be updating; the canvas is still the raw 1200x750, but the crop shape is 901 x 421.
![Screen Shot 2020-09-02 at 2 29 18 PM](https://user-images.githubusercontent.com/1154130/92038743-b33fd080-ed28-11ea-9257-c1250e7c92db.png)
4. the flip names are a bit misleading: the "flip horizontally" and "flip vertically" are interchanged.  I the code, the 'v', 'h' are actually for flipping **_about_** the vertical or horizontal axes, respectively.

**Comment by joelvbernier** [comment] 2020-09-02 21:49
Adding to this, the reference tilts are also not being assigned to the different image plates.  For the LLNL instruments, the tilt parameterization is always going to be intrinsic zxz, and my reference instruments have the default tilt parameters for the as-loaded orientations of the detector borders.  

Further, rotating the cropped image array (I don't think it is actually doing the image interpolation to pull the raw canvas data onto the rotated crop canvas...) should update the third tilt parameter (in the intrinsic zxz params) as that is precisely the rotation of the image plate about it's own normal.

**Comment by joelvbernier** [comment] 2020-09-02 23:28
Another change request:

For the TARDIS, let's use the following detector keys, as they match the data taxonomy in the archive:

- IMAGE-PLATE-2
- IMAGE-PLATE-3
- IMAGE-PLATE-4

For PXRDIP:

- IMAGE-PLATE-L
- IMAGE-PLATE-D
- IMAGE-PLATE-R
- IMAGE-PLATE-U
- IMAGE-PLATE-B

For BBXRD:

- LFT
- DWN
- RGT
- TOP
- BCK

**Comment by joelvbernier** [comment] 2020-09-16 22:45
Ok, @bnmajor new stuff:

Something werid going on with the tilt parameter initialization.  I repeatedly get these (see below) tilt angles for IP2 after importing TARDIS data -- and this is without applying any rotation.  They should be (180, 90, 180), or equivalently (0, -90, 0).

![tilt_init_error](https://user-images.githubusercontent.com/1154130/93397748-15232e80-f82f-11ea-9a8a-117fd8ae0632.png)

IMAGE-PLATE-4 looks fine.

At the end of the day, we want to update the last angle only (from the reference values) with the angle input using the "rotate" button.

**Comment by joelvbernier** [comment] 2020-09-16 22:47
side note @bnmajor (and @cjh1 and @johnkit): the "Loading Processed Imageseries" dialog appears after import and hangs around like a zombie widget (see bottom right in the pic above).  Can't close it.

**Comment by joelvbernier** [comment] 2020-09-16 23:19
I'll note that it is importing the reference values correctly:

![Screenshot from 2020-09-16 16-05-49](https://user-images.githubusercontent.com/1154130/93401239-97fbb780-f836-11ea-9e2f-5e766a7e4fba.png)

They are just getting erroneously munged.

**Comment by joelvbernier** [comment] 2020-09-16 23:20
Also, sub-issue: when applying a transform to the image in the I/O widget, the colormap gets reset.  This should be disabled.

**Comment by cjh1** [comment] 2020-09-16 23:20
@johnkit Can you take care of the zombie please?

**Comment by joelvbernier** [comment] 2020-09-16 23:30
@cjh1 @johnkit : it appears after clicking the "complete and reload instrument" button.  Then just stays.  This is on Ubuntu.

**Comment by bnmajor** [comment] 2020-09-17 04:31
@joelvbernier The bug with `IP2` was caused by two issues: the defaults were being pulled from `IP4` instead of `IP2`, and the conversion to `instrinsic zxz` was then called on those values (which were already `instrinsic zxz`). This appears to be corrected in #526. Here's a screenshot of the config (with the added rotation) and polar view for the re-loaded `TARDIS` instrument:
![tardis-polar](https://user-images.githubusercontent.com/51238406/93420457-ed5ab780-f87c-11ea-8672-6cc96d9ce86f.png)

**Comment by psavery** [comment] 2020-09-17 11:07
> side note @bnmajor (and @cjh1 and @johnkit): the "Loading Processed Imageseries" dialog appears after import and hangs around like a zombie widget (see bottom right in the pic above). Can't close it.

I've seen this before occasionally as well, for progress dialogs in other parts of the code. It didn't happen consistently for me, but I never tracked down the reason for it when it did happen.

**Comment by cjh1** [comment] 2020-09-17 12:06
> when applying a transform to the image in the I/O widget, the colormap ranges get reset. This should be disabled.

I will break this out into an issue

**Comment by cjh1** [comment] 2020-09-17 15:02
> side note @bnmajor (and @cjh1 and @johnkit): the "Loading Processed Imageseries" dialog appears after import and hangs around like a zombie widget (see bottom right in the pic above). Can't close it.

I have created #530 for this

**Comment by cjh1** [comment] 2020-09-28 13:54
Closing this, I think the issues are now resolve, or broken off into there own issues.

**Closed by cjh1** 2020-09-28 13:54 UTC
Labels: bug, high priority, llnl
