### ISSUE TITLE
On mac, pop-up windows do not remain in front

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#335] opened 2020-06-09 19:31 UTC
The materials table and the line-picked calibration zoom box are two different pop-up windows that should remain in front of the main window at all times.

This works fine on Linux, but on Mac, if you click on the main window, the pop-up windows are moved to the back.

We should fix this so the pop-up windows remain in the front for Mac as well.

This was first reported in [this comment](https://github.com/HEXRD/hexrdgui/pull/324#issuecomment-641512885).

**Comment by cryos** [comment] 2020-06-09 20:31
This is not a bug, it is a feature of macOS. The behavior is to conform to Apple's standards, we should perhaps use sheets instead but we hit this in several other projects.

**Comment by psavery** [comment] 2020-07-01 20:53
We can try to look into sheets and drawers. It looks like you can set [a window flag](https://doc.qt.io/qt-5/qt.html#WindowType-enum) for the dialog to use this.

**Comment by psavery** [comment] 2020-07-01 21:56
It looks like [Qt::Tool windows](https://doc.qt.io/qt-5/qt.html#WindowType-enum) remain in front as well.

For reference, two dialogs of interest are:

[The materials table](https://github.com/HEXRD/hexrdgui/blob/fe5c58068995e4f3b09f87017d581cfc3325bd55/hexrd/ui/materials_table.py#L10)
===================
![materials_table](https://user-images.githubusercontent.com/9558430/86295194-09c34e00-bbc4-11ea-81cd-745fe1238807.gif)

[The line picker dialog](https://github.com/HEXRD/hexrdgui/blob/fe5c58068995e4f3b09f87017d581cfc3325bd55/hexrd/ui/line_picker_dialog.py#L14)
=====================
![calibration_line_picker](https://user-images.githubusercontent.com/9558430/86295211-1182f280-bbc4-11ea-96c3-6912710a5548.gif)

**Comment by johnkit** [comment] 2020-07-02 12:51
Yes, the `Qt::WindowStaysOnTopHint` flag appears to do what we are looking for. I can show you guys later this morning (I'm offline until 10am or so).

**Comment by johnkit** [comment] 2020-07-02 15:04
After a little more exploration, on macOS
* the `Qt::WindowStaysOnTopHint` flag works per se, put the window is on top until you close it, even if you minimize the app.
* the `Qt::Tool` flag also keeps the popup on top. It has its own minimize control separate from the main app. Better but not ideal. Will look into it a bit further.

**Comment by johnkit** [comment] 2020-07-02 17:26
1\. I learned from Bob that macOS applications have a "hide" option in the native application menu (command-H), which is how users would typically hide (minimize) all windows open for a given application.

2\. As for the minimize button in the menu bar, I am pretty sure Qt also has a way to capture when it is clicked. We should be then be able to send the command-H key event to hide (minimize) all of the open application windows. I'll hack something up to give it a try, probably later today.

**Comment by cjh1** [comment] 2020-07-02 17:36
@johnkit Lets just use the `Qt::Tool` and move on, we can make improvements in the future if necessary.

**Comment by johnkit** [comment] 2020-07-02 19:01
Sorry I got distracted on some other projects. I'll double-check that the PR doesn't hose linux.

**Comment by cjh1** [comment] 2020-07-02 19:06
It worked good for me

**Comment by johnkit** [comment] 2020-07-02 19:08
Thanks, turns out that I will need to build py3.8 on my dusty Ubuntu 16.04 machine before I can run the gui. Maybe I'll stick on macOS anyway so we have more exposure there.

**Comment by cjh1** [comment] 2020-07-02 19:18
You can probably install from a PPA, https://websiteforstudents.com/how-to-install-python-3-8-on-ubuntu-18-04-16-04/

**Closed** 2020-07-02 23:40 UTC
