### ISSUE TITLE
Calibration error in shape_base.py

### ISSUE THREAD

**Issue by zixuanye** [HEXRD/hexrdgui#715] opened 2021-01-22 15:55 UTC
Hi Joel! I got the attached error while calibrating the instrument. My system is macOS Catalina. Thanks!

Traceback (most recent call last):
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/calibration_runner.py", line 137, in finish_line
    self.pick_next_line()
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/calibration_runner.py", line 101, in pick_next_line
    self.finish()
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/calibration_runner.py", line 212, in finish
    self.run_calibration()
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/calibration_runner.py", line 221, in run_calibration
    instr_calibrator = run_calibration(picks, instr, materials)
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/pick_based_calibration.py", line 457, in run_calibration
    x1, cox_x, infodict, mesg, ierr = leastsq(
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 410, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 24, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/pick_based_calibration.py", line 436, in residual
    calib.residual(
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/pick_based_calibration.py", line 356, in residual
    return self._evaluate(reduced_params, data_dict)
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/hexrd/ui/calibration/pick_based_calibration.py", line 323, in _evaluate
    pdata = np.vstack(pdata)
  File "<__array_function__ internals>", line 5, in vstack
  File "/Users/zixuanye/opt/anaconda3/envs/hexrd/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate

**Comment by joelvbernier** [comment] 2021-01-28 02:14
Looks like the calibration routine is seeing no points selected (which are stored in `pdata` above).  Were you using the two-click method and not selecting points in the zoom window?  Any information you have w.r.t. how to reproduce this would be helpful :-)

**Comment by psavery** [comment] 2022-05-20 21:18
Closing this, as it has been a long time, and changes to hexrdgui may have fixed it. Feel free to re-open if the issue is encountered again on the latest.

**Closed by psavery** 2022-05-20 21:18 UTC
